---
# Configure network interface settings
- name: Configure network interface
  ansible.windows.win_shell: |
    New-NetIPAddress -InterfaceAlias "{{ win_var_network.interface }}" -IPAddress {{ win_var_network.address }} -PrefixLength {{ win_var_network.prefix }} -DefaultGateway {{ win_var_network.gateway }}
  when: win_var_network is defined
