---
- name: Add User
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    state: "{{ item.state }}"
    password: "{{ item.password | password_hash('sha512') }}"
  loop: "{{ rhel9_var_user }}"
  when: rhel9_var_user is defined
  become: true
