---
- name: Stop firewalld
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  loop: "{{ rhel9_var_firewalld }}"
  when: rhel9_var_firewalld is defined
  become: true
