---
- name: Check subscription-manager.conf
  ansible.builtin.shell:
    grep ^enabled=0 /etc/yum/pluginconf.d/subscription-manager.conf
  register: command_result
  changed_when: false
  failed_when: false
  become: true
- name: Set subscription-manager.conf
  ansible.builtin.shell:
    sed -i -e 's/^enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf
  changed_when: false
  when: command_result.rc
  become: true
- name: Yum UpdateSecurity
  yum:
    name: '*'
    security: true
    state: latest
  become: true
