---
- name: Configure account lockout in system-auth
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^auth.*pam_faillock.so'
    line: "auth        required      pam_faillock.so preauth silent deny={{ rhel9_var_account_lockout_attempts }} unlock_time=900"
    backrefs: yes
  when: rhel9_var_account_lockout_attempts is defined
  become: true

- name: Configure account lockout in password-auth
  ansible.builtin.lineinfile:
    path: /etc/pam.d/password-auth
    regexp: '^auth.*pam_faillock.so'
    line: "auth        required      pam_faillock.so preauth silent deny={{ rhel9_var_account_lockout_attempts }} unlock_time=900"
    backrefs: yes
  when: rhel9_var_account_lockout_attempts is defined
  become: true
